[package]
name = "pamtpmpin-common"
version = "0.1.1"
edition = "2024"

[dependencies]
tss-esapi = "7.6.0"
zeroize = "1.0"
tss-esapi-sys = "0.5.0"

[dev-dependencies]
tempfile = "3.8"
serial_test = "3.0"
